### ISSUE TITLE
issue relating a tag

### ISSUE THREAD

**Issue by Pr4th** [ZacharyBuffone/UnityGrapplingHookComponent#1]
![sdasd](https://user-images.githubusercontent.com/52172131/71785624-bf279700-2fcf-11ea-8882-8d0d17ec6bd7.JPG)

where is this tag supposed to be added

**Comment by tijon1** [comment]
you need to add a variable called GRAPPLING_NODE_TAG and replace some of the code to reference the variable.

**Comment by harryrook** [comment]
@tijon1 Could you add any more context on what kind of variable I'd need add? And what aspect of the code needs adjusting?
